### ISSUE TITLE
Problems when executing PlateFlex

### ISSUE THREAD

**Issue by DarbyLima** [paudetseis/PlateFlex#8]
Hi Dr. Pascal Audet,

I'm tring to use PlateCurie but when installing the envinonment for PlateFlex, some issues occous as the messagem "WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.

I'm wondering why this and I guess is due to some incompatibilty between Pymc3 3.10 and Theano. What version of Theano is compatible with Pymc3 3.10.

After installing PlateFelz in a new environment, this message is shown on screen:

(pflex) d:\PlateFlex>python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:45) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import plateflex
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\PlateFlex\plateflex\__init__.py", line 157, in <module>
    from . import estimate
  File "d:\PlateFlex\plateflex\estimate.py", line 57, in <module>
    from plateflex.flex import flex
ModuleNotFoundError: No module named 'plateflex.flex'

It looks like plateflex does not exits or is in conflict with some package.
This is the list of all the packages installed on the environment:

(pflex) d:\PlateFlex>pip list
Package              Version
-------------------- ---------
anyio                3.5.0
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
arviz                0.11.1
asttokens            2.0.5
attrs                21.4.0
Babel                2.9.1
backcall             0.2.0
beautifulsoup4       4.11.1
bleach               4.1.0
brotlipy             0.7.0
certifi              2022.6.15
cffi                 1.15.1
cftime               1.5.0
charset-normalizer   2.0.4
cloudpickle          2.1.0
colorama             0.4.5
cryptography         37.0.1
cycler               0.11.0
cytoolz              0.12.0
dask                 2022.8.1
debugpy              1.5.1
decorator            5.1.1
defusedxml           0.7.1
dill                 0.3.5.1
entrypoints          0.4
executing            0.8.3
fastjsonschema       2.16.2
fastprogress         1.0.3
fonttools            4.37.1
fsspec               2022.7.1
idna                 3.3
imageio              2.21.1
importlib-metadata   4.11.4
importlib-resources  5.2.0
ipykernel            6.9.1
ipython              8.4.0
ipython-genutils     0.2.0
ipywidgets           7.6.5
jedi                 0.18.1
Jinja2               3.0.3
json5                0.9.6
jsonschema           4.4.0
jupyter              1.0.0
jupyter-client       7.2.2
jupyter-console      6.4.3
jupyter-core         4.10.0
jupyter-server       1.18.1
jupyterlab           3.4.4
jupyterlab-pygments  0.1.2
jupyterlab-server    2.12.0
jupyterlab-widgets   1.0.0
kiwisolver           1.4.4
locket               1.0.0
Mako                 1.2.1
MarkupSafe           2.1.1
matplotlib           3.4.2
matplotlib-inline    0.1.2
mistune              0.8.4
mkl-service          2.4.0
munkres              1.1.4
nbclassic            0.3.5
nbclient             0.5.13
nbconvert            6.4.4
nbformat             5.3.0
nest-asyncio         1.5.5
netCDF4              1.5.7
networkx             2.8.6
notebook             6.4.12
numpy                1.17.5
packaging            21.3
pandas               1.2.4
pandocfilters        1.5.0
parso                0.8.3
partd                1.3.0
patsy                0.5.2
pickleshare          0.7.5
Pillow               9.2.0
pip                  22.2.2
plateflex            0.1.0
ply                  3.11
prometheus-client    0.14.1
prompt-toolkit       3.0.20
pure-eval            0.2.2
pycparser            2.21
Pygments             2.11.2
pygpu                0.7.6
pymc3                3.10.0
pyOpenSSL            22.0.0
pyparsing            3.0.9
PyQt5                5.15.7
PyQt5-sip            12.11.0
pyrsistent           0.18.0
PySocks              1.7.1
python-dateutil      2.8.2
pytz                 2022.2.1
PyWavelets           1.1.1
pywin32              302
pywinpty             2.0.2
PyYAML               6.0
pyzmq                23.2.0
qtconsole            5.3.1
QtPy                 2.0.1
requests             2.28.1
scikit-image         0.16.2
scipy                1.7.0
seaborn              0.11.2
Send2Trash           1.8.0
setuptools           58.0.0
sip                  6.6.2
six                  1.16.0
sniffio              1.2.0
soupsieve            2.3.1
stack-data           0.2.0
statsmodels          0.12.2
terminado            0.13.1
testpath             0.6.0
Theano-PyMC          1.0.11
toml                 0.10.2
toolz                0.12.0
tornado              6.2
traitlets            5.1.1
typing-extensions    3.10.0.2
unicodedata2         14.0.0
urllib3              1.26.11
wcwidth              0.2.5
webencodings         0.5.1
websocket-client     0.58.0
wheel                0.37.1
widgetsnbextension   3.5.2
win-inet-pton        1.1.0
xarray               0.19.0
zipp                 3.8.1

**Comment by DarbyLima** [comment]
Hi Dr. Pascal Audet!
I found out a solution! The issue was caused by a conflict between theano and numpy. I tested several versions of numpy (1.17.0 to 1.21.0) Then the correct version is numpy 1.21.0! (^_^)
Now, I'm face another little problem... (-_-')... Save the results on a .txt file.....

**Comment by paudetseis** [comment]
@DarbyLima fantastic!! Thanks for your solution, and sorry I wasn't able to get to this sooner. I will keep the issue open in case someone else comes across this problem. 

Do you mean you need to save the results, or the intermediate steps? I'm assuming you are talking about `PlateCurie`? You can check out the method `save_results()` of the `Project` class if you only need to save the grids of results as a `.csv` file: https://paudetseis.github.io/PlateCurie/classes.html#project

**Comment by DarbyLima** [comment]
Thank you very much, Dr. Pascal! It worked!
